spring:
  application:
    name: ehr-template
  profiles:
    active: dev

server:
  port: 8888

#dev
---
spring:
  profiles: dev

logging:
  path: c:/logs/ehr-template

#prod
---
spring:
  profiles: prod

logging:
  path: /tmp/logs/ehr-template